### ISSUE TITLE
特にイベント情報取得部分の JavaScript 整備

### ISSUE THREAD

**Issue by xtetsuji** [perl-entrance-org/perl-entrance-org.github.com#48]
課題

- jQuery が古いどころか、2つの異なるバージョンの jQuery を読んでいるっぽい
- Zusaar や Doorkeeper のコードはさすがにもう削っていいのでは
- JavaScript コードを HTML 中ではなく外部ファイルに追い出したい
- クライアントで読み込むと JSONP で複数のイベント情報を取得するために同時並列的にAPIを叩くが、connpass 的に少し待ちを入れたほうがいいのかも
- Copyright 表記の最新年部分の更新は面倒なので、JavaScript で最新年が差し込まれるようにする？

**Comment by xtetsuji** [comment]
ちなみに IE のアクセスはほぼ全て IE11 なので、jQuery も効率が良い 3 系にして良さそう。

**Comment by sironekotoro** [comment]
公式サイトのJS、先のタグの整合性の時にどうしようかと思っていました。
connpassから取ってくるやつ、jQueryはわからんのですが、Vue.jsでならできそう・・・と思ったのでやってみて良いですかね？

あと、jQueryがふたつ呼ばれるのは
- スライドショー＆CSSのスマホ対応
- connpassから持ってくるやつ
の2つなのかなー、と思っておりました。

CSSも、重量級のfoundationってやつを使っているけど、もう少し軽量級のにしたいです・・・が、こっちはまったく自信なし。

**Comment by xtetsuji** [comment]
jQuery に依存している foundation を外せるのであれば jQuery を外せると思いますが、それができないのであれば jQuery と Vue の並列はつらいので、無理せず Vue 化しなくてもいいかなと思いました。

**Comment by sironekotoro** [comment]
言われてみれば確かに・・・というか、自分でも2つのJSライブラリを扱う覚悟がなかった・・・

**Comment by xtetsuji** [comment]
いったん私の方で、jQuery 内作業を進めます。

同時に foundation の把握も進めて、手軽に jQuery 非依存の代替軽量モジュールへ置き換え可能であれば Vue 化を進めましょう。jQuery → Vue でのタスクは、値バインディング部分と Ajax コードの修正のみと思っています。

jQuery を3系にするのであれば、待ちを入れる処理のところは Vue とよく一緒に使われるらしい axios を意識した書き方に変更しておきます。

**Comment by sironekotoro** [comment]
Vueでいけるか試してた時のやつです。備忘録的に貼ります。
axiosと、JSONPを実現するための`axiosJsonpAdapter`をつかっています。

https://gist.github.com/sironekotoro/bc9e85d0d19eb5a0bac6f5e518592dbd

URLというか、connpassイベントのIDがあれば、現在公式ページに掲載している情報は全部持ってこられそうです

**Comment by xtetsuji** [comment]
connpass イベントURLだけ設定すれば全てのイベント名を展開するようにするのもいいかなと思ったのですが、connpass API がアクセス不能だと真っ白になってしまう問題もあるよなぁという部分で葛藤中です。

折衷案として、connpass イベントURL（もしくはID）を与えると地域別イベント領域に固定情報のデータを埋める更新用Perlスクリプトを用意するとかでしょうかね。

IEは11のみなのですが（そもそも個人向けにサポートされているIEは現在11のみ）、Google Analytics によると全体にみるIEの割合が15%ほどあって、そうなるとES2015の構文が軒並み使えないのは意識しないとなと考えています。「イベントに関連する数値といった動的更新部分だけダメになるくらいなら、IE11非対応でもいい」と割り切る案もありますが…。ちなみに TypeScript 導入は、他のサポーターの更新のハードルが高くなるのでなるべくなら導入したくないな（私一人が管理しているサイトであれば導入してみようと思うのですが）という気分です。

**Comment by sironekotoro** [comment]
あー、connpass APIが不調だった時のことは考えてなかったです。
不調ではなくとも、メンテが入る時は当然あるだろうし、なるほど。

**Comment by xtetsuji** [comment]
#49 で修正中です。

Foundation をちらっと調べてみたのですが、完全に jQuery 前提としているライブラリのようですね。Foundation で何をやっているか調べて、jQuery を使わない代替ライブラリに移行できるかという話になってきそうですが、ちょっと重そうですね。

**Comment by xtetsuji** [comment]
Copyright 表記は、フッターの address 要素の中にあるものを動的に書き換えることは簡単ですが、meta 要素の copyright は検索エンジンのボットで回収されるときに静的に現在年になっている必要がある事に気づきました。そうであれば、JavaScript による方法論ではなく、毎年年始に更新を忘れずにする別の仕組みのほうがいいかも。

**Comment by xtetsuji** [comment]
Copyright 部分は #50 にある通り、現在年は不要ということで削除することになり解決しました。

その他の JavaScript 改修は #49 のマージで完了しています。

 レスポンシブデザインのための Foundation が jQuery 依存な部分、jQuery を特段排除しなければならない明確な理由もないので、最新の jQuery にしたところでいったん対応済みとしたいと思います。
